(() => {
  "use strict";
  const SUPABASE_URL="https://uftqqchwdksznxsjioat.supabase.co";
  const SUPABASE_KEY="sb_publishable_b3D290QZUx-TwJHj7D_s-A_PzYdGNxw";
  const GROUP_KEY="fairwash_group",LOCAL_KEY="fairwash_v6_local";
  const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
  let group=null,channel=null,saveTimer=null,saving=false,saveAgain=false,state=defaults();
  const $=id=>document.getElementById(id);

  function defaults(){return{participantCount:2,names:["Christoph","Ramona","Person 3","Person 4","Person 5"],factors:{amount:2,fat:2,difficulty:2},history:[],raffled:null}}
  function normalize(value){const s=value&&typeof value==="object"?value:{},d=defaults(),names=Array.isArray(s.names)?s.names.map(String):d.names;while(names.length<5)names.push(`Person ${names.length+1}`);return{participantCount:Math.min(5,Math.max(2,Number(s.participantCount)||2)),names:names.slice(0,5),factors:{amount:Number(s.factors?.amount)||2,fat:Number(s.factors?.fat)||2,difficulty:Number(s.factors?.difficulty)||2},history:Array.isArray(s.history)?s.history:[],raffled:Number.isInteger(s.raffled)?s.raffled:null}}
  function toast(message){const e=$("toast");e.textContent=message;e.className="toast show";clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.className="toast",1900)}
  function tokenFrom(value){const raw=String(value||"").trim();try{return new URL(raw).searchParams.get("group")||""}catch{return raw.replace(/^.*group=/,"").split(/[&#]/)[0]}}
  async function ensureAuth(){const {data,error}=await db.auth.getSession();if(error)throw error;if(!data.session){const r=await db.auth.signInAnonymously();if(r.error)throw r.error}}
  async function init(){try{await ensureAuth();$("bootStatus").textContent="Bereit.";const token=new URL(location.href).searchParams.get("group")||localStorage.getItem(GROUP_KEY);if(token)await joinGroup(token,true)}catch(error){$("bootStatus").textContent=`Verbindung fehlgeschlagen: ${error.message}`}}
  async function createGroup(){const name=$("groupName").value.trim();if(!name)return toast("Bitte einen Gruppennamen eingeben.");try{await ensureAuth();$("createBtn").disabled=true;const r=await db.rpc("create_fairwash_group",{group_name:name,initial_state:state});if(r.error)throw r.error;openGroup(r.data[0]);toast("Gruppe erstellt.")}catch(error){toast(`Erstellen fehlgeschlagen: ${error.message}`)}finally{$("createBtn").disabled=false}}
  async function joinGroup(rawToken,silent=false){const token=tokenFrom(rawToken);if(!token){if(!silent)toast("Bitte Link oder Gruppencode eingeben.");return}try{await ensureAuth();const r=await db.rpc("join_fairwash_group",{token});if(r.error)throw r.error;openGroup(r.data[0]);if(!silent)toast("Gruppe beigetreten.")}catch(error){if(silent){localStorage.removeItem(GROUP_KEY);$("bootStatus").textContent="Gespeicherte Gruppe konnte nicht geöffnet werden."}else toast("Gruppe nicht gefunden oder Zugriff fehlgeschlagen.")}}
  function openGroup(data){group=data;state=normalize(data.state);localStorage.setItem(GROUP_KEY,data.invite_token);localStorage.setItem(LOCAL_KEY,JSON.stringify(state));history.replaceState(null,"",`${location.pathname}?group=${data.invite_token}`);$("landing").classList.add("hidden");$("mainApp").classList.remove("hidden");$("currentGroup").textContent=data.name;const link=`${location.origin}${location.pathname}?group=${data.invite_token}`;$("inviteLink").textContent=link;$("qrImage").src=`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(link)}`;subscribe();render(false)}
  function subscribe(){if(channel)db.removeChannel(channel);channel=db.channel(`fairwash-${group.group_id}`).on("postgres_changes",{event:"UPDATE",schema:"public",table:"fairwash_groups",filter:`id=eq.${group.group_id}`},payload=>{state=normalize(payload.new.state);localStorage.setItem(LOCAL_KEY,JSON.stringify(state));$("syncStatus").textContent="Gerade aktualisiert";render(false)}).subscribe(status=>{if(status==="SUBSCRIBED")$("syncStatus").textContent="Live verbunden"})}
  function queueSave(){localStorage.setItem(LOCAL_KEY,JSON.stringify(state));$("syncStatus").textContent="Speichert …";clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,300)}
  async function saveCloud(){if(!group)return;if(saving){saveAgain=true;return}saving=true;const snapshot=JSON.parse(JSON.stringify(state));const r=await db.from("fairwash_groups").update({state:snapshot}).eq("id",group.group_id);saving=false;if(r.error){$("syncStatus").textContent="Offline – lokal gespeichert";toast("Cloud-Speicherung fehlgeschlagen.")}else $("syncStatus").textContent="Synchronisiert";if(saveAgain){saveAgain=false;saveCloud()}}

  function totals(){const scores=Array(state.participantCount).fill(0),counts=Array(state.participantCount).fill(0);state.history.forEach(e=>{if(e.person>=0&&e.person<scores.length){scores[e.person]+=Number(e.points)||0;counts[e.person]++}});return{scores,counts}}
  function candidates(){const {scores}=totals(),min=Math.min(...scores);return scores.map((v,i)=>v===min?i:-1).filter(i=>i>=0)}
  function nextPerson(){const list=candidates();if(state.raffled!==null&&list.includes(state.raffled))return state.raffled;if(!state.history.length)return list[0];const last=state.history[state.history.length-1].person;for(let step=1;step<=state.participantCount;step++){const candidate=(last+step)%state.participantCount;if(list.includes(candidate))return candidate}return list[0]}
  function renderStats(){const values=state.history.map(e=>Number(e.points)||0),sum=values.reduce((a,b)=>a+b,0);$("statCount").textContent=values.length;$("statAverage").textContent=(values.length?sum/values.length:0).toLocaleString("de-DE",{minimumFractionDigits:1,maximumFractionDigits:1});$("statMax").textContent=values.length?Math.max(...values):0}
  function render(save=true){const data=totals(),next=nextPerson();$("participantCount").value=state.participantCount;$("heroName").textContent=state.names[next];$("washValue").textContent=Number(state.factors.amount)+Number(state.factors.fat)+Number(state.factors.difficulty);const players=$("players");players.innerHTML="";const maximum=Math.max(...data.scores),minimum=Math.min(...data.scores);for(let i=0;i<state.participantCount;i++){const card=document.createElement("div");card.className=`player${i===next?" active":""}${data.scores[i]===maximum&&maximum>minimum?" high":""}`;card.innerHTML=`<input class="name-input" aria-label="Name Person ${i+1}"><div class="score">${data.scores[i]} Punkte</div><div class="count">${data.counts[i]} Abwasche</div><div class="badge">${i===next?"Als Nächstes":data.scores[i]===maximum&&maximum>minimum?"Meiste Punkte":"Aktuell fair"}</div>`;const input=card.querySelector("input");input.value=state.names[i];input.onchange=()=>{state.names[i]=input.value.trim()||`Person ${i+1}`;render()};players.appendChild(card)}
    const spread=maximum-minimum,lowNames=data.scores.map((v,i)=>v===minimum?state.names[i]:null).filter(Boolean),fairness=$("fairness");if(spread<=2){fairness.className="fairness green";fairness.textContent="🟢 Alles fair 👍"}else if(spread<=5){fairness.className="fairness yellow";fairness.textContent=`🟡 Leichter Vorteil für ${lowNames.join(", ")}`}else{fairness.className="fairness red";fairness.textContent=`🔴 ${lowNames.join(", ")} ${lowNames.length>1?"sollten":"sollte"} jetzt übernehmen.`}
    const list=candidates(),draw=$("drawBtn");draw.classList.toggle("hidden",list.length<=1);draw.textContent=`🎲 Zwischen ${list.length} Personen auslosen`;
    document.querySelectorAll(".choices").forEach(g=>g.querySelectorAll(".choice").forEach(b=>b.classList.toggle("selected",Number(b.dataset.value)===Number(state.factors[g.dataset.factor]))));renderStats();renderHistory();if(save)queueSave()}
  function renderHistory(){const h=$("history");h.innerHTML="";if(!state.history.length){h.innerHTML='<div class="muted" style="text-align:center">Noch kein Abwasch eingetragen.</div>';return}for(let i=state.history.length-1;i>=0;i--){const e=state.history[i],row=document.createElement("div");row.className="entry";row.innerHTML=`<div class="entry-top"><div><div class="entry-name"></div><div class="muted">M ${e.amount} · F ${e.fat} · S ${e.difficulty}</div></div><div class="entry-points">+${e.points}</div></div><div class="entry-actions"><button class="mini">Bearbeiten</button><button class="mini danger">Löschen</button></div>`;row.querySelector(".entry-name").textContent=state.names[e.person]||`Person ${e.person+1}`;const buttons=row.querySelectorAll("button");buttons[0].onclick=()=>{const value=prompt("Neue Punkte (3–9):",e.points);if(value!==null&&Number(value)>=3&&Number(value)<=9){e.points=Number(value);state.raffled=null;render();toast("Eintrag geändert.")}};buttons[1].onclick=()=>{if(confirm("Eintrag löschen?")){state.history.splice(i,1);state.raffled=null;render();toast("Eintrag gelöscht.")}};h.appendChild(row)}}

  document.querySelectorAll(".choice").forEach(button=>button.onclick=()=>{state.factors[button.parentNode.dataset.factor]=Number(button.dataset.value);render()});
  $("createBtn").onclick=createGroup;$("joinBtn").onclick=()=>joinGroup($("joinCode").value);
  $("participantCount").onchange=function(){if(state.history.length&&!confirm("Dabei wird der Verlauf gelöscht. Fortfahren?")){this.value=state.participantCount;return}state.participantCount=Number(this.value);state.history=[];state.raffled=null;render()};
  $("drawBtn").onclick=()=>{const list=candidates();if(list.length<=1)return;state.raffled=list[Math.floor(Math.random()*list.length)];render();toast(`${state.names[state.raffled]} wurde ausgelost.`)};
  $("addBtn").onclick=()=>{const person=nextPerson(),amount=Number(state.factors.amount),fat=Number(state.factors.fat),difficulty=Number(state.factors.difficulty);state.history.push({person,amount,fat,difficulty,points:amount+fat+difficulty,createdAt:new Date().toISOString()});state.raffled=null;render();toast("✅ Abwasch eingetragen.")};
  $("undoBtn").onclick=()=>{if(!state.history.length)return toast("Kein Eintrag vorhanden.");state.history.pop();state.raffled=null;render();toast("Letzter Eintrag entfernt.")};
  $("resetBtn").onclick=()=>{if(!state.history.length)return toast("Der Verlauf ist bereits leer.");if(confirm("Wirklich alles löschen?")){state.history=[];state.raffled=null;render();toast("Verlauf gelöscht.")}};
  $("shareToggle").onclick=()=>$("shareBox").classList.toggle("hidden");$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("inviteLink").textContent);toast("Link kopiert.")}catch{toast("Link bitte manuell kopieren.")}};$("leaveBtn").onclick=()=>{localStorage.removeItem(GROUP_KEY);history.replaceState(null,"",location.pathname);location.reload()};
  init();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
})();